site_name: pypmsi

repo_url: https://github.com/GuillaumePressiat/pypmsi

theme:
  name: material
  language: fr
  logo: assets/rigologo_pypmsi.png
  favicon: assets/rigologo_pypmsi.png
  features:
    - content.code.copy
    - navigation.footer


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/GuillaumePressiat/pypmsi
    - icon: fontawesome/brands/pied-piper-alt
      link: https://guillaumepressiat.github.io
    
copyright: Copyright &copy; 2023 Guillaume Pressiat


